package todo.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;

/**
 * JPA Entity representing a Todo item stored in the database.
 * <p>
 * Maps to a database table with fields for description, status,
 * creation time, optional due date, and completion time.
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TodoItem {

    /**
     * Unique identifier of the todo item.
     * <p>
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Description of the todo item.
     */
    private String description;

    /**
     * Current status of the todo item.
     * <p>
     * Stored as a string in the database. Possible values defined in {@link TodoStatus}:
     * "NOT_DONE", "DONE", "PAST_DUE".
     */
    @Enumerated(EnumType.STRING)
    private TodoStatus status;

    /**
     * Timestamp when the todo was created.
     */
    private Instant createdAt;

    /**
     * Optional due date of the todo item.
     * <p>
     * Can be null if not set.
     */
    private Instant dueDate;

    /**
     * Timestamp when the todo was marked as done.
     * <p>
     * Null if the todo is not completed yet.
     */
    private Instant doneAt;
}